---
service: image-resize

custom:
  bucketName: bsoille-resized-images-bucket-${opt:stage, 'dev'}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  stackName: ${opt:stage, 'dev'}-${self:service}
  memorySize: 512
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
  environment:
    S3_BUCKET: ${self:custom.bucketName}
  tracing:
    apiGateway: true
    lambda: true

  # IAM configuration to let the lambda access to S3 bucket.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucketName}/*"
plugins:
  - serverless-plugin-cloudwatch-dashboard

functions:
  image-resize:
    handler: app.lambdaHandler
    events:
      - http:
          method: post
          path: /image

dashboard:
  lambda:
    enabled: true

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
